### ISSUE TITLE
EGS and GOG stores not loading

### ISSUE THREAD

**Issue by dfrazao** [vogler/free-games-claimer#117]
Recently I've been having an issue where either EGS or GOG doesn't load, resulting in both timing out. 

This is the output from docker:
```
2023-03-31 15:19:22 fgc  | Xvfb display server created screen with resolution 1280x1280
2023-03-31 15:19:22 fgc  | VNC is running on port 5900 (no password!)
2023-03-31 15:19:22 fgc  | noVNC (VNC via browser) is running on http://localhost:6080
2023-03-31 15:19:22 fgc  | 
2023-03-31 15:19:23 fgc  | 2023-03-31 14:19:23.181 started checking epic-games
2023-03-31 15:20:25 fgc  | page.goto: Timeout 60000ms exceeded.
2023-03-31 15:20:25 fgc  | =========================== logs ===========================
2023-03-31 15:20:25 fgc  | navigating to "https://store.epicgames.com/en-US/free-games", waiting until "domcontentloaded"
2023-03-31 15:20:25 fgc  | ============================================================
2023-03-31 15:20:25 fgc  |     at file:///fgc/epic-games.js:55:14 {
2023-03-31 15:20:25 fgc  |   name: 'TimeoutError'
2023-03-31 15:20:25 fgc  | }
2023-03-31 15:20:26 fgc  | 2023-03-31 14:20:26.653 started checking prime-gaming
2023-03-31 15:21:28 fgc  | page.goto: Timeout 60000ms exceeded.
2023-03-31 15:21:28 fgc  | =========================== logs ===========================
2023-03-31 15:21:28 fgc  | navigating to "https://gaming.amazon.com/home", waiting until "domcontentloaded"
2023-03-31 15:21:28 fgc  | ============================================================
2023-03-31 15:21:28 fgc  |     at file:///fgc/prime-gaming.js:36:14 {
2023-03-31 15:21:28 fgc  |   name: 'TimeoutError'
2023-03-31 15:21:28 fgc  | }
1970-01-01 01:00:00 fgc exited with code 1
```

If there's anything else I can share about my configuration, that can help fix this issue, I'll gladly share it. Or, if there is anything I can try to resolve from my end, I can do that, as well.

**Comment by vogler** [comment]
Looks like something about your setup changed and now it doesn't have internet access anymore.
Connect via VNC and see what happens if you visit the URLs manually in the browser.

**Comment by dfrazao** [comment]
I checked other containers I have running and it seems that you are right, they don't have internet access, I hadn't noticed before, thanks. I'll close this issue, then!
