### ISSUE TITLE
Claiming Prime Gaming DLC returns multiple elements. 

### ISSUE THREAD

**Issue by BGarber42** [vogler/free-games-claimer#136]
When trying to claim a game, the CSS Selector returns multiple matching elements. 

Related #55

```
locator.getAttribute: Error: strict mode violation: locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a') resolved to 2 elements:
    1) <a data-a-target="learn-more-card" data-a-selector=…>…</a> aka getByRole('link', { name: 'Go to NFL Draft Ultimate Team Pack offer' })
    2) <a class="tw-interactive tw-button" href="/draft-ul…>…</a> aka getByRole('link', { name: 'Go to NFL Draft Ultimate Team Pack offer' }).getByRole('link', { name: 'Claim' })

=========================== logs ===========================
waiting for locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a')
============================================================
    at file:///fgc/prime-gaming.js:262:66
    at async file:///fgc/prime-gaming.js:259:18
```

**Comment by vogler** [comment]
Should have been fixed together with its duplicate #142 by https://github.com/vogler/free-games-claimer/commit/290fe289d4dac79e595f5bddf9ed54a72dd75a2a.
