### ISSUE TITLE
Epic Games Timeout already claimed Game - Prime Error

### ISSUE THREAD

**Issue by freewebnow** [vogler/free-games-claimer#159]
In my case, I already have Hunter Call of the Wild.
But it shows an error message instead, and not that it is already in the library.

I don't have Idle Champions of the Forgotten Realms yet.
But unfortunately there is no order.

```
2023-06-23 04:58:52.881 started checking epic-games
Signed in as XXX
Free games: [
  'https://store.epicgames.com/en-US/p/idle-champions-of-the-forgotten-realms',
  'https://store.epicgames.com/en-US/p/thehunter-call-of-the-wild'
]
page.goto: Timeout 60000ms exceeded.
=========================== logs ===========================
navigating to "https://store.epicgames.com/en-US/p/idle-champions-of-the-forgotten-realms", waiting until "load"
============================================================
    at file:///fgc/epic-games.js:121:16 {
  name: 'TimeoutError'
}
2023-06-23 05:00:35.339 started checking prime-gaming
Signed in as XXX
Number of already claimed games (total): 11
Number of free unclaimed games (Prime Gaming): 1
Current free game: Autonauts
Number of free unclaimed games (external stores): 3
Current free game: Prey
  External store: gog.com
  Code to redeem game: XXX
  URL to redeem game: https://www.gog.com/redeem
elementHandle.$: Protocol error (Page.adoptNode): error in channel "content::3/4/5": exception while running method "adoptNode" in namespace "page": Cannot find object with id = id-133 unsafeObject@chrome://juggler/content/content/FrameTree.js:540:11
_adoptNode@chrome://juggler/content/content/PageAgent.js:367:28
_onMessageInternal@chrome://juggler/content/SimpleChannel.js:222:37
_onMessage@chrome://juggler/content/SimpleChannel.js:191:12
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:54:44
 _onMessageInternal@chrome://juggler/content/SimpleChannel.js:206:24
_onMessage@chrome://juggler/content/SimpleChannel.js:191:12
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:54:44

    at file:///fgc/prime-gaming.js:125:37 {
  name: 'Error'
}
```

**Comment by vogler** [comment]
Can't reproduce. How are you running it? Did you try again? Is the hardware too slow?

Run with `RECORD=1` to get a recording in `data/record` or check via VNC or with `SHOW=1`.

You can also increase the timeout with e.g. `TIMEOUT=120`, but I think 60s should be enough even on slow machines.

**Comment by vogler** [comment]
Concerning prime-gaming `elementHandle.$: Protocol error (Page.adoptNode)`: should be fixed with 85513031f2d03478a9ed833cc4e9fa9a8fd24ed4, so you're likely running an outdated image.

**Comment by freewebnow** [comment]
Hello,

thank you.

Actually, the current image is always loaded.
A timeout does not occur now.

```
latest: Pulling from vogler/free-games-claimer
Digest: sha256:7905134bae1a9fcee9305638d99a5f7f731a40c9be0785fd54e2e58cdfc95329
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-06-24 04:55:38.616 started checking epic-games
Signed in as XXX
Free games: [
  'https://store.epicgames.com/en-US/p/idle-champions-of-the-forgotten-realms',
  'https://store.epicgames.com/en-US/p/thehunter-call-of-the-wild'
]
  This game contains mature content recommended only for ages 18+
Current free game: Idle Champions of the Forgotten Realms
  Not in library yet! Click GET.
  Claimed successfully!
Current free game: theHunter: Call of the Wild™
  Already in library! Nothing to claim.
2023-06-24 04:56:41.091 started checking prime-gaming
Signed in as XXX
Number of already claimed games (total): 33
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 2
Current free game: Revita
  External store: amazon games
elementHandle.$: Protocol error (Page.adoptNode): error in channel "content::3/4/5": exception while running method "adoptNode" in namespace "page": Cannot find object with id = id-95 unsafeObject@chrome://juggler/content/content/FrameTree.js:540:11
_adoptNode@chrome://juggler/content/content/PageAgent.js:367:28
_onMessageInternal@chrome://juggler/content/SimpleChannel.js:222:37
_onMessage@chrome://juggler/content/SimpleChannel.js:191:12
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:54:44
 _onMessageInternal@chrome://juggler/content/SimpleChannel.js:206:24
_onMessage@chrome://juggler/content/SimpleChannel.js:191:12
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:54:44

    at file:///fgc/prime-gaming.js:125:37 {
  name: 'Error'
}
2023-06-24 04:57:12.471 started checking gog
Signed in as XXX
Currently no free giveaway!

``` 

I run the whole thing as a task in Synology.

```
docker run --rm -i -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
```

**Comment by vogler** [comment]
I'll close this as it seems to be resolved.
