### ISSUE TITLE
Problem with running scripts

### ISSUE THREAD

**Issue by wielorzeczownik** [vogler/free-games-claimer#202]
Scripts quits at the same place
============================================================
**Description:**
I am not able to run any of the scripts. Each script stops at the same place and completes the task in an identical way, here is an example for epic games.

```
latest: Pulling from vogler/free-games-claimer
Digest: sha256:4311ba75f64c3ff0535235ed2509169ec61d0243e5d3286bedb79f9d01170d36
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
Version: https://github.com/vogler/free-games-claimer/tree/38975e811bac5133a0895ae450de7a7a5a3f2b9d
Build: Thu, 31 Aug 2023 21:09:15 +0000
Xvfb display server created screen with resolution 1920x1080
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-08-23 06:00:37.951 started checking epic-games
page.goto: SEC_ERROR_UNKNOWN
=========================== logs ===========================
navigating to "https://store.epicgames.com/en-US/free-games", waiting until "domcontentloaded"
============================================================
    at file:///fgc/epic-games.js:66:14 {
  name: 'Error'
}
```

**Comment by wielorzeczownik** [comment]
I set the PWDEBUG in env to 1 and got this return:
```
latest: Pulling from vogler/free-games-claimer
Digest: sha256:4311ba75f64c3ff0535235ed2509169ec61d0243e5d3286bedb79f9d01170d36
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
Version: https://github.com/vogler/free-games-claimer/tree/38975e811bac5133a0895ae450de7a7a5a3f2b9d
Build: Thu, 31 Aug 2023 21:09:15 +0000
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-08-24 09:14:57.765 started checking epic-games
node:internal/process/esm_loader:100
    internalBinding('errors').triggerUncaughtException(
                              ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1422/firefox/firefox -no-remote -wait-for-browser -foreground -profile data/browser -juggler-pipe --hide-crash-restore-bubble about:blank
<launched> pid=210
[pid=210][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=210][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=210][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=1.58186) [GFX1-]: glxtest: libpci missing
[pid=210][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=1.58186) |[1][GFX1-]: glxtest: libEGL missing (t=1.58199) [GFX1-]: glxtest: libEGL missing
[pid=210][out]
[pid=210][out] Juggler listening to the pipe
============================================================
    at async file:///fgc/epic-games.js:25:17

Node.js v19.9.0
```

**Comment by wielorzeczownik** [comment]
I used the image from docker hub and it started working
