### ISSUE TITLE
Epic : unrated games

### ISSUE THREAD

**Issue by traveltrousers** [vogler/free-games-claimer#245]

**Comment by traveltrousers** [comment]
Current game fails 

https://store.epicgames.com/en-US/p/turnip-boy-commits-tax-evasion-fb2084

Turnip Boy Commits Tax Evasion contains content that is unrated and may not be appropriate for all ages.


Docker logs shows :

Free games: [
  'https://store.epicgames.com/en-US/p/turnip-boy-commits-tax-evasion-fb2084'
]
--- Exception:
page.goto: Timeout 60000ms exceeded.
=========================== logs ===========================
navigating to "https://store.epicgames.com/en-US/p/turnip-boy-commits-tax-evasion-fb2084", waiting until "load"
============================================================
    at /fgc/epic-games.js:137:16 {
  name: 'TimeoutError'
}

**Comment by traveltrousers** [comment]
Free games: [
  'https://store.epicgames.com/en-US/p/turnip-boy-commits-tax-evasion-fb2084'
]
  This game contains mature content recommended only for ages 18+
Current free game: Turnip Boy Commits Tax Evasion
  Not in library yet! Click GET.
locator.waitFor: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('text=Thanks for your order!')
============================================================
    at /fgc/epic-games.js:231:59 {
  name: 'TimeoutError'
}
  Failed to claim! To avoid captchas try to get a new IP address.

**Comment by traveltrousers** [comment]
OK so I watched it though VNC this time and it times out right before the 'order' is finished processing...

Can I slightly increase the timeout manually?

Running in an overworked docker on a rPi4

**Comment by traveltrousers** [comment]
I increased the timeout by using the docker console to edit the config.js file to 120 seconds....

fingers crossed

**Comment by traveltrousers** [comment]
180 seconds got me to a captcha :p

will add to the spreadsheet
