### ISSUE TITLE
Exception when trying to claim games from Epic

### ISSUE THREAD

**Issue by wolfyllow** [vogler/free-games-claimer#319]
Hi! 

I'm getting the following error trying to claim games from Epic store:
```
--- Exception:
locator.innerText: Timeout 60000ms exceeded.
Call log:
  - waiting for locator('h1').first()
```
It's happening with the game Lisa, which to me appears with a different layout than other game pages in the [Epic store](https://store.epicgames.com/es-ES/bundles/lisa-the-definitive-edition).

Anyone with the same issue?
Cheers

**Comment by N-acetylcysteine** [comment]
exact same case here

**Comment by N-acetylcysteine** [comment]
Free games: [
  'https://store.epicgames.com/en-US/p/industria',
  'https://store.epicgames.com/en-US/bundles/lisa-the-definitive-edition'
]
Current free game: INDUSTRIA
  Not in library yet! Click GET.
  Claimed successfully!
--- Exception:
locator.innerText: Timeout 60000ms exceeded.
Call log:
  - waiting for locator('h1').first()

    at C:\Users\JoeBiden\Desktop\free games\free-games-claimer\epic-games.js:162:52

**Comment by floxigen** [comment]
I've same issue as well

**Comment by Mrgaton** [comment]
same

```
--- Exception:
locator.innerText: Timeout 60000ms exceeded.
Call log:
  - waiting for locator('h1').first()

    at C:\Users\mrgaton\Mega\games-claimer\free-games-claimer\epic-games.js:162:52 {
  name: 'TimeoutError'
}
```

**Comment by Mrgaton** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/68958481/4dd8fc6f-d05a-45ef-b5cd-6dc73c82eb66)

**Comment by vogler** [comment]
Seems like I fixed this in 3338d08a1d29584d7a209656b17266cd19b06c7a. Have to check again when there's a bundle.
