### ISSUE TITLE
GOG #menuUsername hidden with low width

### ISSUE THREAD

**Issue by ccsimplyspolit** [vogler/free-games-claimer#335]
```
main
2024-06-23 19:51:43.359 started checking gog
--- Exception:
[AggregateError: All promises were rejected] {
  [errors]: [
    locator.waitFor: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('a:has-text("Sign in")').first() to be visible
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>

        at D:\claim_games\FGC\free-games-claimer\gog.js:41:29,
    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#menuUsername') to be visible
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" class="men…></span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" class="men…></span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>

        at D:\claim_games\FGC\free-games-claimer\gog.js:41:45
  ]
}
```

**Comment by vogler** [comment]
Format logs with ```.
Seems like the login locator changed. Are you logged in?

**Comment by ccsimplyspolit** [comment]
yes, i'm logged in

**Comment by ccsimplyspolit** [comment]
yes i'm logged in

вс, 23 июн. 2024 г. в 21:47, Ralf Vogler ***@***.***>:

**Comment by vogler** [comment]
Can't reproduce. Works fine for me.

It seems that for you neither of the two locators is visible.
Run with `SHOW=1` to open the browser or `RECORD=1` to record a video.

**Comment by vogler** [comment]
What's your resolution? Maybe the username is hidden if you don't have enough width.

**Comment by ccsimplyspolit** [comment]
set WIDTH=840
set HEIGHT=840


also have error when use set RECORD=1

**Comment by vogler** [comment]
> set WIDTH=840

That's the problem then. Why did you set it that low?

> also have error when use set RECORD=1

What's the error?

**Comment by vogler** [comment]
The username menu is even attached to the DOM when not logged in, that's why it relies on visibility:
![image](https://github.com/vogler/free-games-claimer/assets/493741/e745cce8-2322-483f-9baf-90214c2657c8)

I'll just make it error out for width < 1280 (seems like it breaks <1100).
