### ISSUE TITLE
set RECORD=1 error

### ISSUE THREAD

**Issue by ccsimplyspolit** [vogler/free-games-claimer#336]
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/a373637f-46e1-45f1-ab24-971a39e523e5)
```
2024-06-25 14:37:41.398 started checking gog
Signed in as sshunko
Currently no free giveaway!
Recorded video: D:\claim_games\FGC\free-games-claimer\data\record\63f6bb8d-6da4-4647-96a4-d2adbbdbaca6.webm
node:internal/modules/run_main:115
    triggerUncaughtException(
    ^

ENOENT: no such file or directory, copyfile 'C:\Users\sshunko\AppData\Local\Temp\playwright-artifacts-XXXXXXWEsTt8\9dd94c1a042d3bf23974f7c4f026acd7.har' -> 'D:\claim_games\FGC\free-games-claimer\data\record\gog-2024-06-25 14:37:41.400.har'
    at D:\claim_games\FGC\free-games-claimer\async file:\D:\claim_games\FGC\free-games-claimer\gog.js:155:1 {
  name: 'Error'
}

```

```
Node.js v22.3.0
2024-06-25 14:37:47.328 started checking prime-gaming
Signed in as Sergey
User is currently not an Amazon Prime member, so no games to claim. Exit!
--- Exception:
ENOENT: no such file or directory, copyfile 'C:\Users\sshunko\AppData\Local\Temp\playwright-artifacts-XXXXXXScmElA\2b8341f736aa483c7789b2ac774011bf.har' -> 'D:\claim_games\FGC\free-games-claimer\data\record\pg-2024-06-25 14:37:47.331.har'
    at D:\claim_games\FGC\free-games-claimer\async file:\D:\claim_games\FGC\free-games-claimer\prime-gaming.js:96:5 {
  name: 'Error'
}
Recorded video: D:\claim_games\FGC\free-games-claimer\data\record\c964f7f6-47ba-4d45-bc33-843c3ba5516c.webm

```

**Comment by vogler** [comment]
Thanks, forgot to replace the `:` in har filenames which are not allowed on Windows.
