### ISSUE TITLE
No chromium browser installed

### ISSUE THREAD

**Issue by ironic833** [vogler/free-games-claimer#351]
Hey there I am receiving the following:

```latest: Pulling from vogler/free-games-claimer
Digest: sha256:0587364e8780ae0fe590b0a5d10ed11dd56106a14cef12368b869a0b8d8c53e2
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
Version: https://github.com/vogler/free-games-claimer/tree/11db31ea46bf1fd0ec67144f484d3b151ba569b5
Build: Mon, 06 Nov 2023 18:41:08 +0000
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (with password)
noVNC (VNC via browser) is running on http://localhost:6080

2024-07-28 11:05:49.556 started checking epic-games
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1425/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe --hide-crash-restore-bubble about:blank
<launched> pid=224
[pid=224][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=224][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=224][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=1.87075) [GFX1-]: glxtest: libpci missing
[pid=224][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=1.87075) |[1][GFX1-]: glxtest: libEGL missing (t=1.87075) [GFX1-]: glxtest: libEGL missing
[pid=224][out]
[pid=224][out] Juggler listening to the pipe
============================================================
    at /fgc/async file:/fgc/epic-games.js:23:17

Node.js v20.9.0
2024-07-28 11:06:05.676 started checking prime-gaming
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1425/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe about:blank
<launched> pid=662
[pid=662][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=662][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=662][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=4.78476) [GFX1-]: glxtest: libpci missing
[pid=662][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=4.78476) |[1][GFX1-]: glxtest: libEGL missing (t=4.78476) [GFX1-]: glxtest: libEGL missing
[pid=662][out]
[pid=662][out] Juggler listening to the pipe
============================================================
    at /fgc/async file:/fgc/prime-gaming.js:16:17

Node.js v20.9.0
2024-07-28 11:06:30.485 started checking gog
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1425/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe about:blank
<launched> pid=1082
[pid=1082][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=1082][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=1082][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=4.27019) [GFX1-]: glxtest: libpci missing
[pid=1082][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=4.27019) |[1][GFX1-]: glxtest: libEGL missing (t=4.27019) [GFX1-]: glxtest: libEGL missing
[pid=1082][out]
[pid=1082][out] Juggler listening to the pipe
============================================================
    at /fgc/async file:/fgc/gog.js:14:17```

**Comment by vogler** [comment]
> Build: Mon, 06 Nov 2023 18:41:08 +0000

You pulled the latest tag which isn't updated by CI anymore.
Pull without tag as written in the readme.
