### ISSUE TITLE
prime-gaming failed: elementHandle.screenshot: Element is not attached to the DOM

### ISSUE THREAD

**Issue by SnakeEater96** [vogler/free-games-claimer#357]
2024-08-02T20:00:57.600344823Z Number of already claimed games (total): 17
2024-08-02T20:00:57.757828257Z Number of free unclaimed games (Prime Gaming): 3
2024-08-02T20:00:58.479580322Z Current free game: Tomb Raider: The Last Revelation + Chronicles
2024-08-02T20:00:59.831036645Z --- Exception:
2024-08-02T20:00:59.836251179Z elementHandle.screenshot: Element is not attached to the DOM
2024-08-02T20:00:59.836276324Z Call log:
2024-08-02T20:00:59.836280894Z   - taking element screenshot
2024-08-02T20:00:59.836285127Z   - waiting for fonts to load...
2024-08-02T20:00:59.836289035Z   - fonts loaded
2024-08-02T20:00:59.836312569Z   - attempting scroll into view action
2024-08-02T20:00:59.836316557Z   -   waiting for element to be stable
2024-08-02T20:00:59.836320381Z 
2024-08-02T20:00:59.836324190Z     at /fgc/prime-gaming.js:159:16 {
2024-08-02T20:00:59.836328139Z   name: 'Error'
2024-08-02T20:00:59.836332446Z }
2024-08-02T20:01:02.712788956Z 2024-08-02 20:01:02.711 started checking gog
2024-08-02T20:01:18.064957436Z Signed in as SnakeEater96
2024-08-02T20:01:18.182201173Z Currently no free giveaway!
2024-08-02T20:01:19.716583270Z sleeping

**Comment by voruti** [comment]
I had this problem as well over the last few days, but (at least for me) seems to be fixed now.

**Comment by SnakeEater96** [comment]
problem still exists

**Comment by SnakeEater96** [comment]
2024-08-03T22:31:52.494296963Z Number of free unclaimed games (Prime Gaming): 3
2024-08-03T22:31:53.164747408Z Current free game: Tomb Raider: The Last Revelation + Chronicles
2024-08-03T22:31:53.968568449Z --- Exception:
2024-08-03T22:31:53.989964549Z elementHandle.screenshot: Element is not attached to the DOM
2024-08-03T22:31:53.990002711Z Call log:
2024-08-03T22:31:53.990008180Z   - taking element screenshot
2024-08-03T22:31:53.990011853Z   - waiting for fonts to load...
2024-08-03T22:31:53.990015639Z   - fonts loaded
2024-08-03T22:31:53.990019098Z   - attempting scroll into view action
2024-08-03T22:31:53.990022549Z   -   waiting for element to be stable
2024-08-03T22:31:53.990026332Z 
2024-08-03T22:31:53.990029773Z     at /fgc/prime-gaming.js:159:16 {
2024-08-03T22:31:53.990033268Z   name: 'Error'
2024-08-03T22:31:53.990036735Z }
2024-08-03T22:31:56.365407507Z 2024-08-03 22:31:56.363 started checking gog

**Comment by Stoony1** [comment]
same here epic not work yet.

**Comment by SnakeEater96** [comment]
> same here epic not work yet.

Epic funktioniert schon länger nicht ist aber bekannt und gibt einen langen Beitrag dazu

**Comment by SnakeEater96** [comment]
Prime Gaming wasn't running smoothly for me


2024-08-05T21:05:16.790446932Z waitUntilStable 15
2024-08-05T21:05:21.822619521Z waitUntilStable 16
2024-08-05T21:05:26.849537978Z waitUntilStable 16
2024-08-05T21:05:26.870887436Z Number of already claimed games (total): 16
2024-08-05T21:05:26.901676228Z Number of free unclaimed games (Prime Gaming): 0
2024-08-05T21:05:26.902041561Z Number of free unclaimed games (external stores): 0
2024-08-05T21:05:31.107711248Z Trying to claim in-game content...
2024-08-05T21:05:31.956500613Z Loading all DLCs on page...waitUntilStable 1
2024-08-05T21:05:31.976291386Z 
2024-08-05T21:05:31.976333265Z Number of already claimed DLC: 1
2024-08-05T21:05:31.990337104Z Number of unclaimed DLC: 0
2024-08-05T21:05:31.991441222Z DLC: Unlinked accounts: {}
2024-08-05T21:05:32.069268947Z node:internal/process/promises:391
2024-08-05T21:05:32.069328854Z     triggerUncaughtException(err, true /* fromPromise */);
2024-08-05T21:05:32.069334339Z     ^
2024-08-05T21:05:32.069338126Z 
2024-08-05T21:05:32.069341893Z page.waitForTimeout: Target page, context or browser has been closed
2024-08-05T21:05:32.069346177Z     at /fgc/prime-gaming.js:113:16
2024-08-05T21:05:32.069349675Z     at async waitUntilStable (/fgc/prime-gaming.js:107:7)
2024-08-05T21:05:32.069427696Z 
2024-08-05T21:05:32.069452048Z Node.js v20.16.0

**Comment by vogler** [comment]
@SnakeEater96 Do you still have the screenshot issue?

**Comment by vogler** [comment]
@ironic833 Yea, loading all games has become unreliable since it skipped right to the end of the page which also skipped loading for some games in-between. Now it scrolls more like a human towards the end with some waits in-between. A bit hacky, but seems to work reliably.

**Comment by yashendra2797** [comment]
Apologies for the necro post, but I am getting this issue on Windows whether I use a browser or not. Any way I can troubleshoot this?
