### ISSUE TITLE
EPIC: Error: Cannot find module 'ms'

### ISSUE THREAD

**Issue by Mrgaton** [vogler/free-games-claimer#373]
node:internal/modules/cjs/loader:1225
  const err = new Error(message);
              ^

Error: Cannot find module 'ms'

**Comment by Mrgaton** [comment]
```log
2024-08-26 17:49:57.495 started checking epic-games
Adding webgl.disabled to C:\Users\username\AppData\Local\games-claimer-browser\prefs.js
node:internal/modules/cjs/loader:1225
  const err = new Error(message);
              ^

Error: Cannot find module 'ms'
Require stack:
- C:\Users\username\AppData\Local\global_node_modules\.pnpm\debug@4.3.4\node_modules\debug\src\common.js
- C:\Users\username\AppData\Local\global_node_modules\.pnpm\debug@4.3.4\node_modules\debug\src\node.js
- C:\Users\username\AppData\Local\global_node_modules\.pnpm\debug@4.3.4\node_modules\debug\src\index.js
- C:\Users\username\AppData\Local\global_node_modules\.pnpm\puppeteer-extra-plugin@3.2.3\node_modules\puppeteer-extra-plugin\dist\index.cjs.js
- C:\Users\username\AppData\Local\global_node_modules\.pnpm\puppeteer-extra-plugin-stealth@2.11.2\node_modules\puppeteer-extra-plugin-stealth\evasions\chrome.app\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at setup (C:\Users\username\AppData\Local\global_node_modules\.pnpm\debug@4.3.4\node_modules\debug\src\common.js:14:25)
    at Object.<anonymous> (C:\Users\username\AppData\Local\global_node_modules\.pnpm\debug@4.3.4\node_modules\debug\src\node.js:240:37)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\username\\AppData\\Local\\global_node_modules\\.pnpm\\debug@4.3.4\\node_modules\\debug\\src\\common.js',
    'C:\\Users\\username\\AppData\\Local\\global_node_modules\\.pnpm\\debug@4.3.4\\node_modules\\debug\\src\\node.js',
    'C:\\Users\\username\\AppData\\Local\\global_node_modules\\.pnpm\\debug@4.3.4\\node_modules\\debug\\src\\index.js',
    'C:\\Users\\username\\AppData\\Local\\global_node_modules\\.pnpm\\puppeteer-extra-plugin@3.2.3\\node_modules\\puppeteer-extra-plugin\\dist\\index.cjs.js',
    'C:\\Users\\username\\AppData\\Local\\global_node_modules\\.pnpm\\puppeteer-extra-plugin-stealth@2.11.2\\node_modules\\puppeteer-extra-plugin-stealth\\evasions\\chrome.app\\index.js'
  ]
}

Node.js v20.17.0
```

**Comment by Mrgaton** [comment]
Same with unreal engine

**Comment by Mrgaton** [comment]
and with prime gaming

**Comment by Mrgaton** [comment]
pnpm useless fault

**Comment by vogler** [comment]
What was the issue?
You installed dependencies with pnpm instead of npm and then it didn't work? Haven't tried it with pnpm, but I don't see why it should not work.
Module `ms` looks like it should be `ms-playwright` in some path, but I don't see that appearing in the log you posted.

**Comment by Mrgaton** [comment]
I was using pnpm install instead of npm
