### ISSUE TITLE
Prime gaming error

### ISSUE THREAD

**Issue by ceszkraft** [vogler/free-games-claimer#384]
Already in library! Nothing to claim.
2024-09-20 17:54:23.050 started checking prime-gaming
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSONFile.parse (<anonymous>)
    at JSONFile.read (file:///fgc/node_modules/lowdb/lib/adapters/node/DataFile.js:17:31)
    at async Low.read (file:///fgc/node_modules/lowdb/lib/core/Low.js:16:22)
    at async JSONFilePreset (file:///fgc/node_modules/lowdb/lib/presets/node.js:9:5)
    at async file:///fgc/prime-gaming.js:14:12

Node.js v20.17.0

On browser I can't even see prime page. What should I do to log in into prime gaming ?

**Comment by ceszkraft** [comment]
I just reinstalled docker and it works :)
