### ISSUE TITLE
Aliexpress - Not working anymore

### ISSUE THREAD

**Issue by 0nnyx** [vogler/free-games-claimer#391]
**Update : Since December 2024, Aliexpress coin collection is no longer possible using a web browser. It's only available through the Android/IOS App**

Having observed this behavior over 2 months, aliexpress requires to manually authenticate every 15 days despite claiming the coins daily.
There is probably no fix for this and likely due to aliexpress expiring the session cookie. 
Posting as information rather than bug in case anyone faces this same timeout.

```
auth https://www.aliexpress.com/p/coin-pc-index/index.html
Coins: €25.94
Streak: 15 day streak
Tomorrow: +40

Version: https://github.com/vogler/free-games-claimer/tree/c87deb393eec26b78d7a30bded8859c183ebb278
Build: Fri, 02 Aug 2024 12:03:33 +0000
Xvfb display server created screen with resolution 1920x1080
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

auth https://www.aliexpress.com/p/coin-pc-index/index.html
Not logged in! Will wait for 120s for you to login...

```

**Comment by bodnar07** [comment]
In my case, the script stops here:
`$ node aliexpress
auth https://www.aliexpress.com/p/coin-pc-index/index.html
--- Exception:
[AggregateError: All promises were rejected] {
  [errors]: [
    locator.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('.checkin-button')

        at coins (E:\GitHub\free-games-claimer\aliexpress.js:66:54)
        at E:\GitHub\free-games-claimer\aliexpress.js:96:74
        at E:\GitHub\free-games-claimer\async file:\E:\GitHub\free-games-claimer
\aliexpress.js:90:3 {
      name: 'TimeoutError'
    },
    locator.waitFor: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('.addcoin') to be visible

        at coins (E:\GitHub\free-games-claimer\aliexpress.js:66:88)
        at E:\GitHub\free-games-claimer\aliexpress.js:96:74
        at E:\GitHub\free-games-claimer\async file:\E:\GitHub\free-games-claimer
\aliexpress.js:90:3 {
      name: 'TimeoutError'
    }
  ]
}
`

**Comment by Mrgaton** [comment]
i got the error of captcha when before it wasnt trigering

**Comment by osnapitsjoey** [comment]
how are you guys even getting it to work? I downloaded the aliexpress.js to the docker container, fixed a problem with it looking for utils in the wrong folder, and it still isnt even working

**Comment by 0nnyx** [comment]
I believe it's only possible to get these coins through their mobile app now. 
Browsing to https://www.aliexpress.com/p/coin-pc-index/index.html does not increase my coin amount anymore.
That js file should be deprecated.

**Comment by osnapitsjoey** [comment]
Ahhh okay! And how about the unreal engine assets? I see it's still in the
read me, but no mention of any variables that I can find

**Comment by Iceboy-6** [comment]
Hi guys.

Just some info that could revive this .js for aliexpress.

If you access the exact following link on chrome with a specific mobile user-agent, coins page shows up again in PC/Desktop:

https://m.aliexpress.com/p/coin-index/index.html

UA or another mobile UA equivalent: Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25

![Image](https://github.com/user-attachments/assets/583f7642-8c91-4bb2-8b44-327e748f97e2)

**Comment by vogler** [comment]
AliExpress login and claiming coins should be fixed on the `dev` branch:
<img width="547" height="204" alt="Image" src="https://github.com/user-attachments/assets/8278366f-b6b2-4a4a-919c-a8edd3417ce6" />

@osnapitsjoey Claiming Unreal assets needs to be updated.
