### ISSUE TITLE
Error on claim epic games: `TypeError: Cannot read properties of undefined (reading 'childFrames')`

### ISSUE THREAD

**Issue by caolonghao** [vogler/free-games-claimer#395]
I have an error when trying to claim epic games. The error message is:
```
TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (E:\Code\free-games-claimer\node_modules\playwright-core\lib\server\frames.js:297:31)
    at FrameManager.frameCommittedNewDocumentNavigation (E:\Code\free-games-claimer\node_modules\playwright-core\lib\server\frames.js:147:10)
    at FFPage._onNavigationCommitted (E:\Code\free-games-claimer\node_modules\playwright-core\lib\server\firefox\ffPage.js:165:30)
    at FFSession.emit (node:events:519:28)
    at E:\Code\free-games-claimer\node_modules\playwright-core\lib\server\firefox\ffConnection.js:154:41

Node.js v20.14.0
```
Can reproduce it both on windows and ubuntu24.04 LTS.

**Comment by BlueCl0wn** [comment]
I have the same issue
