### ISSUE TITLE
Playwirght Related Issue?

### ISSUE THREAD

**Issue by codeclinic** [vogler/free-games-claimer#405]
I got this running but now the logs show the following and the container shutsdown.

[19:02:55] INFO: Starting the app with arguments "node epic-games"
Version: https://github.com/vogler/free-games-claimer/tree/c8cf7362fa2ff92386eee4dc847784d95d7f5195
Build: Sat, 31 Aug 2024 23:23:37 +0000
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080/
2024-12-05 19:02:56.446 started checking epic-games
node:internal/modules/run_main:129
triggerUncaughtException(
^
browserType.launchPersistentContext: Executable doesn't exist at /root/.cache/ms-playwright/firefox-1425/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers: ║
║ ║
║ npx playwright install ║
║ ║
║ <3 Playwright Team ║
╚═════════════════════════════════════════════════════════════════════════╝
at /data/async file:/data/epic-games.js:23:17 {
name: 'Error'
}
Node.js v20.17.0
[19:02:56] INFO: Starting the app with arguments "node prime-gaming"
Version: https://github.com/vogler/free-games-claimer/tree/c8cf7362fa2ff92386eee4dc847784d95d7f5195
Build: Sat, 31 Aug 2024 23:23:37 +0000
Xvfb display server created screen with resolution 1280x1280
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080/
2024-12-05 19:02:56.861 started checking prime-gaming
node:internal/modules/run_main:129
triggerUncaughtException(
^
browserType.launchPersistentContext: Executable doesn't exist at /root/.cache/ms-playwright/firefox-1425/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers: ║
║ ║
║ npx playwright install ║
║ ║
║ <3 Playwright Team ║
╚═════════════════════════════════════════════════════════════════════════╝
at /data/async file:/data/prime-gaming.js:16:17 {
name: 'Error'
}
Node.js v20.17.0
[19:02:56] INFO: Starting the app with arguments "node gog"
Version: https://github.com/vogler/free-games-claimer/tree/c8cf7362fa2ff92386eee4dc847784d95d7f5195
Build: Sat, 31 Aug 2024 23:23:37 +0000
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080/
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
2024-12-05 19:02:57.257 started checking gog
node:internal/modules/run_main:129
triggerUncaughtException(
^
browserType.launchPersistentContext: Executable doesn't exist at /root/.cache/ms-playwright/firefox-1425/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers: ║
║ ║
║ npx playwright install ║
║ ║
║ <3 Playwright Team ║
╚═════════════════════════════════════════════════════════════════════════╝
at /data/async file:/data/gog.js:14:17 {
name: 'Error'
}
Node.js v20.17.0
[19:02:57] INFO: All actions concluded. Stopping in 10 seconds.

**Comment by vttc08** [comment]
Try deleting `compatibility.ini` which should be located in the containers `/data/browser`. Either find the file in your local bind mount or use `docker exec` to do it in the container. Then recreate and restart the container.

If that doesn't work you might have delete the data folder and recreate from scratch on a local machine.
