### ISSUE TITLE
[Docker] Prime Gaming TimeoutError waiting for Complete Claim button

### ISSUE THREAD

**Issue by EthanC** [vogler/free-games-claimer#41]
Using the latest Docker image, FGC is now claiming Prime Gaming freebies. It seems to fail on unclaimed games from external stores; in this example, that would be Quake on the Epic Games Store. I believe the script does not properly handle if your external account (Epic) was not connected to your Prime Gaming account at the time of the attempted claim.

`docker-compose.yml`
```yml
version: "3"
services:
  free-games-claimer:
    container_name: free-games-claimer
    image: voglerr/free-games-claimer:latest
    ports:
      - 5900:5900
      - 6080:6080
    volumes:
      - /home/ethan/free-games-claimer:/fgc/data
```

Logs
```
2022-12-25 02:18:18.634 started checking prime-gaming
userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
Signed in.
Number of already claimed games (total): 6
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 2
Current free game: Quake
[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 20000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim now")')
      locator resolved to visible <button data-a-target="AvailableButton" class="tw-intera…>…</button>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #1
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #2
      waiting 20ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #3
      waiting 100ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #4
      waiting 100ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #5
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #6
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #7
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #8
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #9
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #10
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #11
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #12
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #13
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #14
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #15
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #16
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #17
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #18
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #19
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #20
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #21
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #22
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #23
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #24
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #25
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #26
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #27
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #28
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #29
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #30
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #31
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #32
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #33
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #34
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #35
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="ReactModal__Overlay ReactModal__Overlay--…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #36
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #37
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #38
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="tw-flex-nowrap tw-tower tw-tower--240 tw-…>…</div> from <div class="ReactModalPortal">…</div> subtree intercepts pointer events
    retrying click action, attempt #39
      waiting 500ms
    ============================================================
        at file:///fgc/prime-gaming.js:102:29 {
      name: 'TimeoutError'
    },
    page.click: Timeout 20000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Complete Claim")')
    ============================================================
        at file:///fgc/prime-gaming.js:102:73 {
      name: 'TimeoutError'
    }
  ]
}
```

**Comment by vogler** [comment]
This code should handle it, but seems like the check for "Link game account" should be further up:
https://github.com/vogler/free-games-claimer/blob/1c38f730ab6d0a4e6db8e1a2229ab8d7b6c76fd2/prime-gaming.js#L102-L109
I can try it out later.

**Comment by vogler** [comment]
It's now also alternatively waiting for "Link game account" at the beginning, so it should no longer time out.
Don't have an account with epic-games unlinked. Let me know if it doesn't work.
