### ISSUE TITLE
Crash on fetch

### ISSUE THREAD

**Issue by Rilith** [vogler/free-games-claimer#410]
Hi! Thank you for your hard work!

i was trying to use the software on my homeserver using docker-compose but i get these errors:

free-games-claimer  | Version: https://github.com/vogler/free-games-claimer/tree/c8cf7362fa2ff92386eee4dc847784d95d7f5195
free-games-claimer  | Build: Sat, 31 Aug 2024 23:23:37 +0000
free-games-claimer  | Xvfb display server created screen with resolution 1920x1080
free-games-claimer  | VNC is running on port 5900 (no password!)
free-games-claimer  | noVNC (VNC via browser) is running on http://localhost:6080
free-games-claimer  | 
free-games-claimer  | 2024-12-13 22:54:05.416 started checking epic-games
free-games-claimer  | Adding webgl.disabled to /fgc/data/browser/prefs.js
free-games-claimer  | --- Exception:
free-games-claimer  | page.goto: Target page, context or browser has been closed
free-games-claimer  | Call log:
free-games-claimer  |   - navigating to "https://store.epicgames.com/en-US/free-games", waiting until "domcontentloaded"
free-games-claimer  | 
free-games-claimer  |     at /fgc/epic-games.js:73:14
free-games-claimer  | node:internal/modules/run_main:129
free-games-claimer  |     triggerUncaughtException(
free-games-claimer  |     ^
free-games-claimer  | 
free-games-claimer  | browserContext.close: Target page, context or browser has been closed
free-games-claimer  |     at /fgc/async file:/fgc/epic-games.js:319:1
free-games-claimer  | 
free-games-claimer  | Node.js v20.17.0
free-games-claimer  | 2024-12-13 22:54:29.866 started checking prime-gaming
free-games-claimer  | --- Exception:
free-games-claimer  | [AggregateError: All promises were rejected] {
free-games-claimer  |   [errors]: [
free-games-claimer  |     page.waitForSelector: Target page, context or browser has been closed
free-games-claimer  |     Call log:
free-games-claimer  |       - waiting for locator('button:has-text("Sign in")') to be visible
free-games-claimer  |     
free-games-claimer  |         at /fgc/prime-gaming.js:43:117
free-games-claimer  |         at /fgc/prime-gaming.js:43:103,
free-games-claimer  |     page.waitForSelector: Target page, context or browser has been closed
free-games-claimer  |     Call log:
free-games-claimer  |       - waiting for locator('[data-a-target="user-dropdown-first-name-text"]') to be visible
free-games-claimer  |     
free-games-claimer  |         at /fgc/prime-gaming.js:43:117
free-games-claimer  |         at /fgc/prime-gaming.js:43:103
free-games-claimer  |   ]
free-games-claimer  | }
free-games-claimer  | node:internal/modules/run_main:129
free-games-claimer  |     triggerUncaughtException(
free-games-claimer  |     ^
free-games-claimer  | 
free-games-claimer  | browserContext.close: Target page, context or browser has been closed
free-games-claimer  |     at /fgc/async file:/fgc/prime-gaming.js:436:1

![immagine](https://github.com/user-attachments/assets/b0eef2f7-4ab9-4abc-acf7-89d58a2b5007)

**Comment by gcn59** [comment]
Hi, found any solution yet ? I'm having the same problem using casaOS 0.4.15

**Comment by vogler** [comment]
> free-games-claimer | Build: Sat, 31 Aug 2024 23:23:37 +0000

Try running the `dev` tag. If it still crashes, reopen this, it may be a problem with casaOS (HASS strangely also had issues due to the image behaving differently (while it should not care about the host OS)).
