### ISSUE TITLE
[Feature Request] Amazon Prime - Claim in game content 

### ISSUE THREAD

**Issue by Underestimated** [vogler/free-games-claimer#55]
This is more of a nice to have thing, but within the Amazon Games site, a number of developers offer in game content and items (For example Two Point Hospital does every month)
Would there be a way to enable claiming this alongside the free games? 

The delivery mechanism is essentially the same as the existing games we’re claiming, and filtering could potentially be done by the listed game name, which each tile has on it, if we were to define in an environmental variable the names of the games we want to claim content for, then the tool could look for only those, and claim them.

As I said it’s not an urgent request or anything, if possible it would be a great value-add to the existing tool, especially if the existing code can be adapted to grab it with minimal effort.

**Comment by vogler** [comment]
I can check. Maybe some opt-in `CLAIMDLC=1` - don't want the default stuff to fail or generate too much noise due to unlinked accounts etc.

**Comment by sealldeveloper** [comment]
I know for some games like Roblox content it just returns a key, maybe detecting if an account needs to be linked and if so if the account is linked? Seems like alot of work.

**Comment by Underestimated** [comment]
> I know for some games like Roblox content it just returns a key, maybe detecting if an account needs to be linked and if so if the account is linked? Seems like alot of work.

That's pretty much how half amazon prime game claims work anyway, there's already an implementation of that as is, (codes output to console, notifications and screenshots directory) which is why I suggested this as an addition, seeing as the process isn't all that different. The only real changes is choosing how to select the DLC to claim, which is why I suggested using the game title that each card has rendered on it.



> I can check. Maybe some opt-in `CLAIMDLC=1` - don't want the default stuff to fail or generate too much noise due to unlinked accounts etc.

Thanks either way, as I said, more of a nice to have, as I'm having to do that manually. If I were to implement it, I'd make an environment variable for enabling it, and then another for an array of titles to check, which could be compared against the titles listed on the game cards on the amazon dashboard. Then it's on the user to define that properly.

**Comment by EthanC** [comment]
Understood `PG_CLAIMDLC` is experimental, but figured I'd give it a try seeing as it's in the latest release.

@vogler If it's of any use, I get a `TimeoutError` while trying to claim DLC. Additionally, an `undefined` notification is sent.

Logs
```
Number of already claimed DLC: 0
Number of unclaimed DLC: 28
Current DLC: Candy Crush Saga - 20 Gold Bars and more, free with Amazon Prime
page.inputValue: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('input[type="text"]')
============================================================
    at file:///fgc/prime-gaming.js:277:33 {
  name: 'TimeoutError'
}
```

Notification
```
prime-gaming (Ethan):
- Candy Crush Saga - 20 Gold Bars and more, free with Amazon Prime (undefined)
```

**Comment by testeur999** [comment]
Current DLC: Candy Crush Saga - 20 Gold Bars and more, free with Amazon Prime
page.inputValue: Timeout 60000ms exceeded.

web page stay waiting to the qr code, then the time out exited

**Comment by vogler** [comment]
I guess that's where I stopped. It currently detects if an account needs to be linked and if a key is shown to be redeemed, but there are some Games/DLCs that have a different page layout (like Candy Crush with the QR code). Maybe I'll just wrap each iteration in a try/catch such that these edge cases don't stop everything.

**Comment by BGarber42** [comment]
Getting a similar issue in the selectors. 

```
locator.getAttribute: Error: strict mode violation: locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a') resolved to 2 elements:
    1) <a data-a-target="learn-more-card" data-a-selector=…>…</a> aka getByRole('link', { name: 'Go to Extra lives and more offer' })
    2) <a class="tw-interactive tw-button" href="/soda-sag…>…</a> aka getByRole('link', { name: 'Go to Extra lives and more offer' }).getByRole('link', { name: 'Claim' })

=========================== logs ===========================
waiting for locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a')
============================================================
    at file:///fgc/prime-gaming.js:262:66
    at async file:///fgc/prime-gaming.js:259:18
```

**Comment by KairuByte** [comment]
I realize this is not officially supported yet, but I've noticed that while the script does get *into* the in-game content, it is never able to claim the content. It always says that linking is needed. Manual claiming works without a hitch for 99% of the offers.

**Comment by yoshimo** [comment]
you could limit it to games that you linked and own and want to get stuff for.

**Comment by KairuByte** [comment]
The games which *are* linked, still pop as failed due to the game not being linked.
